import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";
const API=import.meta.env.VITE_API_URL??"http://localhost:3000";
type Customer={id:string;name:string;email:string;status:string;expires_at?:string;device_limit:number};
type Device={id:string;name:string;platform:string;active:boolean;last_seen_at:string;customer_name:string;email:string};
type Overview={customers:number;devices:number;catalogItems:number};
function App(){
 const[token,setToken]=useState(sessionStorage.getItem("masterToken")??"");const[section,setSection]=useState("overview");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[msg,setMsg]=useState("");const[overview,setOverview]=useState<Overview|null>(null);const[customers,setCustomers]=useState<Customer[]>([]);const[devices,setDevices]=useState<Device[]>([]);
 const[source,setSource]=useState("");const[sourceName,setSourceName]=useState("Catálogo principal");const[newCustomer,setNewCustomer]=useState({name:"",email:"",password:"",expiresAt:"",deviceLimit:2});
 const request=async(path:string,init:RequestInit={})=>{const r=await fetch(API+path,{...init,headers:{"content-type":"application/json",authorization:"Bearer "+token,...(init.headers||{})}});const d=await r.json();if(r.status===401){sessionStorage.clear();setToken("");throw new Error("Sessão expirada.")}if(!r.ok)throw new Error(d.error??"request_failed");return d};
 async function login(){try{const r=await fetch(API+"/v1/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password,deviceKey:"admin-browser",deviceName:"Painel administrativo",platform:"web"})});const d=await r.json();if(!r.ok||d.user?.role!=="master")throw new Error();sessionStorage.setItem("masterToken",d.accessToken);setToken(d.accessToken);setMsg("")}catch{setMsg("Acesso Master não autorizado.")}}
 async function load(){if(!token)return;try{const[o,c,d]=await Promise.all([request("/v1/admin/overview"),request("/v1/admin/customers"),request("/v1/admin/devices")]);setOverview(o);setCustomers(c);setDevices(d)}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load()},[token]);
 async function createCustomer(){try{await request("/v1/admin/customers",{method:"POST",body:JSON.stringify({...newCustomer,expiresAt:newCustomer.expiresAt||null})});setNewCustomer({name:"",email:"",password:"",expiresAt:"",deviceLimit:2});setMsg("Cliente criado.");await load()}catch(e:any){setMsg(e.message)}}
 async function status(id:string,status:string){try{await request("/v1/admin/customers/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e:any){setMsg(e.message)}}
 async function revoke(id:string){try{await request("/v1/admin/devices/"+id+"/revoke",{method:"PATCH"});await load()}catch(e:any){setMsg(e.message)}}
 async function sync(){try{const d=await request("/v1/admin/catalog/sync",{method:"POST",body:JSON.stringify({name:sourceName,sourceUrl:source})});setMsg(`Catálogo sincronizado: ${d.items} itens.`);await load()}catch{setMsg("Não foi possível sincronizar a fonte.")}}
 if(!token)return <main className="login"><section className="loginCard"><span className="eyebrow">SUPERIPTV MASTER</span><h1>Administração</h1><input placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={login}>Entrar</button>{msg&&<p>{msg}</p>}</section></main>;
 return <main className="admin"><aside><b>SUPERIPTV</b><nav>{[["overview","Visão geral"],["catalog","Catálogo"],["customers","Clientes"],["devices","Dispositivos"]].map(([id,label])=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}>{label}</button>)}</nav><button onClick={()=>{sessionStorage.clear();setToken("")}}>Sair</button></aside><section className="content"><span className="eyebrow">MASTER ADMIN</span><h1>{section==="overview"?"Central de operação":section==="catalog"?"Catálogo":section==="customers"?"Clientes":"Dispositivos"}</h1>{msg&&<p className="notice">{msg}</p>}
 {section==="overview"&&<div className="grid"><article><strong>{overview?.customers??0}</strong><span>Clientes cadastrados</span></article><article><strong>{overview?.devices??0}</strong><span>Dispositivos ativos</span></article><article><strong>{overview?.catalogItems??0}</strong><span>Itens ativos no catálogo</span></article></div>}
 {section==="catalog"&&<div className="grid"><article><strong>Fonte privada autorizada</strong><input value={sourceName} onChange={e=>setSourceName(e.target.value)} placeholder="Nome"/><input value={source} onChange={e=>setSource(e.target.value)} placeholder="URL privada da fonte"/><button onClick={sync}>Sincronizar agora</button></article></div>}
 {section==="customers"&&<><article className="formCard"><strong>Novo cliente</strong><input placeholder="Nome" value={newCustomer.name} onChange={e=>setNewCustomer({...newCustomer,name:e.target.value})}/><input placeholder="E-mail" value={newCustomer.email} onChange={e=>setNewCustomer({...newCustomer,email:e.target.value})}/><input type="password" placeholder="Senha inicial" value={newCustomer.password} onChange={e=>setNewCustomer({...newCustomer,password:e.target.value})}/><input type="datetime-local" value={newCustomer.expiresAt} onChange={e=>setNewCustomer({...newCustomer,expiresAt:e.target.value})}/><input type="number" min="1" value={newCustomer.deviceLimit} onChange={e=>setNewCustomer({...newCustomer,deviceLimit:Number(e.target.value)})}/><button onClick={createCustomer}>Criar cliente</button></article><div className="table">{customers.map(c=><article key={c.id}><div><strong>{c.name}</strong><span>{c.email} · {c.status} · até {c.device_limit} aparelhos</span></div><div>{c.status!=="active"?<button onClick={()=>status(c.id,"active")}>Reativar</button>:<button onClick={()=>status(c.id,"blocked")}>Bloquear</button>}</div></article>)}</div></>}
 {section==="devices"&&<div className="table">{devices.map(d=><article key={d.id}><div><strong>{d.name}</strong><span>{d.customer_name} · {d.platform} · {d.active?"ativo":"revogado"}</span></div>{d.active&&<button onClick={()=>revoke(d.id)}>Revogar</button>}</article>)}</div>}
 </section></main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
