import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";
const API=import.meta.env.VITE_API_URL??"http://localhost:3000";
function App(){const[token,setToken]=useState(sessionStorage.getItem("masterToken")??"");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[msg,setMsg]=useState("");const[source,setSource]=useState("");const[name,setName]=useState("Catálogo principal");
 async function login(){const r=await fetch(API+"/v1/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password,deviceKey:"admin-browser",deviceName:"Painel administrativo",platform:"web"})});const d=await r.json();if(!r.ok||d.user?.role!=="master"){setMsg("Acesso Master não autorizado.");return}sessionStorage.setItem("masterToken",d.accessToken);setToken(d.accessToken);setMsg("")}
 async function sync(){const r=await fetch(API+"/v1/admin/catalog/sync",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+token},body:JSON.stringify({name,sourceUrl:source})});const d=await r.json();setMsg(r.ok?`Catálogo sincronizado: ${d.items} itens.`:"Não foi possível sincronizar a fonte.")}
 if(!token)return <main className="login"><section className="loginCard"><span className="eyebrow">SUPERIPTV MASTER</span><h1>Administração</h1><input placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={login}>Entrar</button>{msg&&<p>{msg}</p>}</section></main>;
 return <main className="admin"><aside><b>SUPERIPTV</b><nav><button>Visão geral</button><button>Catálogo</button><button>Clientes</button><button>Dispositivos</button><button>Planos e acesso</button><button>Auditoria</button></nav><button onClick={()=>{sessionStorage.clear();setToken("")}}>Sair</button></aside><section className="content"><span className="eyebrow">MASTER ADMIN</span><h1>Central de operação</h1><p>A fonte é configurada exclusivamente pelo Master. Clientes recebem somente o catálogo autorizado.</p><div className="grid"><article><strong>Sincronizar catálogo</strong><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome"/><input value={source} onChange={e=>setSource(e.target.value)} placeholder="URL privada da fonte"/><button onClick={sync}>Sincronizar agora</button>{msg&&<span>{msg}</span>}</article><article><strong>Clientes</strong><span>Criação, vencimento, bloqueio e limites de dispositivos via API.</span></article><article><strong>Dispositivos</strong><span>Sessões identificadas e revogáveis.</span></article><article><strong>Catálogo</strong><span>Distribuição central para Mobile, TV e Desktop.</span></article></div></section></main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);