import Fastify from "fastify";
import jwt from "@fastify/jwt";
import cors from "@fastify/cors";
import rateLimit from "@fastify/rate-limit";
import bcrypt from "bcryptjs";
import { createHash, randomBytes } from "node:crypto";
import { Readable } from "node:stream";
import { createInterface } from "node:readline";
import { pool } from "./db.js";
import { decryptSecret, encryptSecret } from "./secrets.js";

type JwtUser={sub:string;role:"master"|"customer";deviceId?:string;sessionVersion?:number;deviceVersion?:number};
type PgError={code?:string;constraint?:string};
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
export function buildApp(){
 const secret=process.env.JWT_SECRET;
 if(process.env.NODE_ENV==="production"&&(!secret||secret.length<32)) throw new Error("JWT_SECRET must contain at least 32 characters in production");
 const production=process.env.NODE_ENV==="production";
 const origins=(process.env.CORS_ORIGINS??"").split(",").map(x=>x.trim()).filter(Boolean);
 if(production&&!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required in production");
 if(production&&!process.env.MASTER_BOOTSTRAP_TOKEN)throw new Error("MASTER_BOOTSTRAP_TOKEN is required in production");
 if(production&&!origins.length)throw new Error("CORS_ORIGINS is required in production");
 if(production&&!process.env.CATALOG_SECRET_KEY)throw new Error("CATALOG_SECRET_KEY is required in production");
 if(production&&!/^https:\/\//i.test(process.env.PUBLIC_API_URL??""))throw new Error("PUBLIC_API_URL must be HTTPS in production");
 const app=Fastify({logger:{redact:{paths:["req.headers.authorization","req.headers.cookie","req.body.password","req.body.refreshToken","req.body.sourceUrl","res.headers.location"],censor:"[REDACTED]"}},bodyLimit:2*1024*1024,trustProxy:process.env.TRUST_PROXY==="true"});
 app.register(jwt,{secret:secret??"development-only-change-me"});
 app.register(cors,{origin:origins.length?origins:false,credentials:false});
 app.register(rateLimit,{global:false,max:100,timeWindow:"1 minute"});
 const auth=async(req:any,reply:any)=>{try{await req.jwtVerify()}catch{return reply.code(401).send({error:"unauthorized"})}const u=req.user as JwtUser;const r=await pool.query("select u.status,u.expires_at,u.session_version,d.active device_active,d.session_version device_version from app_users u left join devices d on d.id=$2 and d.user_id=u.id where u.id=$1",[u.sub,u.deviceId??null]);const x=r.rows[0];if(!x||x.status!=="active"||(x.expires_at&&new Date(x.expires_at)<=new Date())||(u.deviceId&&x.device_active!==true)||(u.sessionVersion??0)!==x.session_version||(u.deviceId&&(u.deviceVersion??0)!==x.device_version))return reply.code(401).send({error:"session_inactive"})};
 const master=async(req:any,reply:any)=>{await auth(req,reply);if(reply.sent)return;const u=req.user as JwtUser;if(u.role!=="master")return reply.code(403).send({error:"master_required"})};
 const audit=async(req:any,action:string,targetType:string,targetId?:string,metadata:any={})=>{const u=req.user as JwtUser;try{await pool.query("insert into admin_audit_log(actor_user_id,action,target_type,target_id,metadata) values($1,$2,$3,$4,$5::jsonb)",[u.sub,action,targetType,targetId??null,JSON.stringify(metadata)])}catch(error){req.log.error({error,action,targetType,targetId},"audit_write_failed")}};
 const dbConflict=(error:unknown)=>{const e=error as PgError;return e?.code==="23505"};
 app.get("/health",async()=>({status:"ok",service:"superiptv-api",version:"0.4.0"}));
 app.post("/v1/bootstrap/master",{config:{rateLimit:{max:5,timeWindow:"15 minutes"}}},async(req:any,reply)=>{
  const expected=process.env.MASTER_BOOTSTRAP_TOKEN;if(!expected||req.headers["x-bootstrap-token"]!==expected)return reply.code(404).send({error:"not_found"});
  const exists=await pool.query("select 1 from app_users where role='master' limit 1");if(exists.rowCount)return reply.code(409).send({error:"master_already_exists"});
  const {name,email,password}=req.body??{};if(!name||!email||!password||String(password).length<10)return reply.code(400).send({error:"invalid_master"});
  const passwordHash=await bcrypt.hash(password,12);const r=await pool.query("insert into app_users(role,name,email,password_hash,device_limit) values('master',$1,$2,$3,5) returning id,name,email,role",[name,email,passwordHash]);return reply.code(201).send(r.rows[0]);
 });
 app.post("/v1/auth/login",{config:{rateLimit:{max:10,timeWindow:"1 minute"}}},async(req:any,reply)=>{const {email,password,deviceKey,deviceName,platform}=req.body??{};if(!email||!password||!deviceKey)return reply.code(400).send({error:"missing_credentials"});
  const r=await pool.query("select * from app_users where lower(email)=lower($1) limit 1",[email]);const user=r.rows[0];if(!user||!(await bcrypt.compare(password,user.password_hash)))return reply.code(401).send({error:"invalid_credentials"});if(user.status!=="active"||(user.expires_at&&new Date(user.expires_at)<=new Date()))return reply.code(403).send({error:"access_inactive"});
  const count=await pool.query("select count(*)::int n from devices where user_id=$1 and active=true",[user.id]);let d=await pool.query("select * from devices where user_id=$1 and device_key=$2",[user.id,deviceKey]);
  if(!d.rows[0]&&count.rows[0].n>=user.device_limit)return reply.code(403).send({error:"device_limit"});
  if(!d.rows[0])d=await pool.query("insert into devices(user_id,device_key,name,platform) values($1,$2,$3,$4) returning *",[user.id,deviceKey,deviceName??"Dispositivo",platform??"unknown"]);
  else if(!d.rows[0].active)return reply.code(403).send({error:"device_blocked"});
  const device=d.rows[0];const bumped=await pool.query("update devices set last_seen_at=now(),session_version=session_version+1 where id=$1 returning session_version",[device.id]);await pool.query("update refresh_sessions set revoked_at=now() where device_id=$1 and revoked_at is null",[device.id]);
  const access=app.jwt.sign({sub:user.id,role:user.role,deviceId:device.id,sessionVersion:user.session_version,deviceVersion:bumped.rows[0].session_version},{expiresIn:"15m"});const refresh=randomBytes(48).toString("base64url");
  await pool.query("insert into refresh_sessions(user_id,device_id,token_hash,expires_at) values($1,$2,$3,now()+interval '30 days')",[user.id,device.id,hash(refresh)]);
  return {accessToken:access,refreshToken:refresh,user:{id:user.id,name:user.name,role:user.role},device:{id:device.id,name:device.name}};
 });
 app.post("/v1/auth/refresh",{config:{rateLimit:{max:30,timeWindow:"1 minute"}}},async(req:any,reply)=>{const token=String(req.body?.refreshToken??"");if(!token)return reply.code(400).send({error:"refresh_required"});const client=await pool.connect();try{await client.query("begin");const r=await client.query("select s.id as session_id,s.user_id,s.device_id,u.role,u.status,u.expires_at as user_expires_at,u.session_version,d.active as device_active,d.session_version as device_version from refresh_sessions s join app_users u on u.id=s.user_id left join devices d on d.id=s.device_id where s.token_hash=$1 and s.revoked_at is null and s.expires_at>now() for update of s",[hash(token)]);const s=r.rows[0];if(!s||s.status!=="active"||s.device_active===false||(s.user_expires_at&&new Date(s.user_expires_at)<=new Date())){await client.query("rollback");return reply.code(401).send({error:"refresh_invalid"})}const next=randomBytes(48).toString("base64url");await client.query("update refresh_sessions set revoked_at=now() where id=$1",[s.session_id]);await client.query("insert into refresh_sessions(user_id,device_id,token_hash,expires_at) values($1,$2,$3,now()+interval '30 days')",[s.user_id,s.device_id,hash(next)]);await client.query("commit");const access=app.jwt.sign({sub:s.user_id,role:s.role,deviceId:s.device_id,sessionVersion:s.session_version,deviceVersion:s.device_version},{expiresIn:"15m"});return {accessToken:access,refreshToken:next}}catch(e){await client.query("rollback");throw e}finally{client.release()}});
 app.post("/v1/auth/logout",async(req:any)=>{const token=String(req.body?.refreshToken??"");if(token)await pool.query("update refresh_sessions set revoked_at=now() where token_hash=$1 and revoked_at is null",[hash(token)]);return {ok:true}});
 app.get("/v1/catalog",{preHandler:auth},async(req:any,reply)=>{const u=req.user as JwtUser;if(u.role!=="customer")return reply.code(403).send({error:"customer_required"});const check=await pool.query("select status,expires_at from app_users where id=$1",[u.sub]);const x=check.rows[0];if(!x||x.status!=="active"||(x.expires_at&&new Date(x.expires_at)<=new Date()))return reply.code(403).send({error:"access_inactive"});const r=await pool.query(`select i.id,i.name,i.group_name as "group",i.logo_url as logo,i.content_type as type,i.description,i.year,i.season_number as "seasonNumber",i.episode_number as "episodeNumber",i.series_name as "seriesName" from catalog_items i left join customer_catalog_groups g on g.user_id=$1 and g.group_name=i.group_name where i.active=true and coalesce(g.allowed,true)=true order by i.group_name,i.name`,[u.sub]);return {items:r.rows}});
 app.post("/v1/play/:id/ticket",{preHandler:auth},async(req:any,reply)=>{const u=req.user as JwtUser;if(u.role!=="customer")return reply.code(403).send({error:"customer_required"});const access=await pool.query("select u.status,u.expires_at,d.active device_active from app_users u left join devices d on d.id=$2 where u.id=$1",[u.sub,u.deviceId??null]);const a=access.rows[0];if(!a||a.status!=="active"||a.device_active===false||(a.expires_at&&new Date(a.expires_at)<=new Date()))return reply.code(403).send({error:"access_inactive"});const exists=await pool.query("select 1 from catalog_items i left join customer_catalog_groups g on g.user_id=$2 and g.group_name=i.group_name where i.id=$1 and i.active=true and coalesce(g.allowed,true)=true",[req.params.id,u.sub]);if(!exists.rowCount)return reply.code(404).send({error:"not_found"});const ticket=app.jwt.sign({sub:u.sub,role:"customer",deviceId:u.deviceId,mediaId:req.params.id,purpose:"playback"},{expiresIn:"90s"});return {url:"/v1/play-ticket/"+encodeURIComponent(ticket),expiresIn:90}});
 app.get("/v1/play-ticket/:ticket",async(req:any,reply)=>{let ticket:any;try{ticket=app.jwt.verify(req.params.ticket)}catch{return reply.code(401).send({error:"ticket_invalid"})}if(ticket.purpose!=="playback"||!ticket.mediaId)return reply.code(401).send({error:"ticket_invalid"});const access=await pool.query("select u.status,u.expires_at,d.active device_active from app_users u left join devices d on d.id=$2 where u.id=$1",[ticket.sub,ticket.deviceId??null]);const a=access.rows[0];if(!a||a.status!=="active"||a.device_active===false||(a.expires_at&&new Date(a.expires_at)<=new Date()))return reply.code(403).send({error:"access_inactive"});const r=await pool.query("select i.stream_url,i.stream_url_encrypted from catalog_items i left join customer_catalog_groups g on g.user_id=$2 and g.group_name=i.group_name where i.id=$1 and i.active=true and coalesce(g.allowed,true)=true",[ticket.mediaId,ticket.sub]);if(!r.rows[0])return reply.code(404).send({error:"not_found"});const streamUrl=r.rows[0].stream_url_encrypted?decryptSecret(r.rows[0].stream_url_encrypted):r.rows[0].stream_url;if(!streamUrl)return reply.code(404).send({error:"not_found"});return reply.redirect(streamUrl)});
 app.post("/v1/admin/catalog/sync",{preHandler:master},async(req:any,reply)=>{
  const {name,sourceUrl}=req.body??{};if(!name||!sourceUrl||!/^https?:\/\//i.test(sourceUrl))return reply.code(400).send({error:"invalid_source"});
  const started=Date.now();const run=await pool.query("insert into catalog_sync_runs(source_name,status) values($1,'running') returning id",[String(name)]);const runId=run.rows[0].id;
  const finish=async(status:"success"|"failed",errorCode:string|null,items:number,bytes:number)=>{await pool.query("update catalog_sync_runs set status=$1,error_code=$2,items=$3,bytes=$4,duration_ms=$5,finished_at=now() where id=$6",[status,errorCode,items,bytes,Date.now()-started,runId])};
  const configuredBytes=Number(process.env.CATALOG_SYNC_MAX_BYTES??50*1024*1024);const configuredItems=Number(process.env.CATALOG_SYNC_MAX_ITEMS??100000);const maxBytes=Number.isFinite(configuredBytes)?Math.max(1024,configuredBytes):50*1024*1024;const maxItems=Number.isFinite(configuredItems)?Math.max(1,Math.floor(configuredItems)):100000;
  let response:Response;try{response=await fetch(sourceUrl,{redirect:"follow",signal:AbortSignal.timeout(30000)})}catch{await finish("failed","source_unavailable",0,0);req.log.warn({runId},"catalog_source_fetch_failed");return reply.code(502).send({error:"source_unavailable"})}
  if(!response.ok||!response.body){await finish("failed","source_unavailable",0,0);return reply.code(502).send({error:"source_unavailable"})}
  const declared=Number(response.headers.get("content-length")??0);if(declared>maxBytes){await finish("failed","catalog_too_large",0,declared);return reply.code(413).send({error:"catalog_too_large"})}
  const client=await pool.connect();let count=0;let bytes=0;let info="";
  const limited=Readable.fromWeb(response.body as any).on("data",(chunk:Buffer|string)=>{bytes+=Buffer.byteLength(chunk);if(bytes>maxBytes)limited.destroy(new Error("catalog_too_large"))});
  try{
   await client.query("begin");await client.query("update catalog_items set active=false");
   const lines=createInterface({input:limited,crlfDelay:Infinity});
   for await(const raw of lines){
    const line=String(raw).trim();if(line.startsWith("#EXTINF")){info=line;continue}if(!line||line.startsWith("#")||!info)continue;
    const channelName=info.substring(info.lastIndexOf(",")+1).trim();const group=/group-title="([^"]*)"/i.exec(info)?.[1]||"Sem categoria";const logo=/tvg-logo="([^"]*)"/i.exec(info)?.[1]||null;
    if(channelName){if(++count>maxItems)throw new Error("catalog_item_limit");const id=hash(line).slice(0,24);const encrypted=encryptSecret(line);await client.query("insert into catalog_items(id,name,group_name,logo_url,stream_url,stream_url_encrypted,content_type,active,updated_at) values($1,$2,$3,$4,null,$5,coalesce((select content_type from catalog_group_types where group_name=$3),'live'),true,now()) on conflict(id) do update set name=excluded.name,group_name=excluded.group_name,logo_url=excluded.logo_url,stream_url=null,stream_url_encrypted=excluded.stream_url_encrypted,content_type=excluded.content_type,active=true,updated_at=now()",[id,channelName,group,logo,encrypted])}
    info="";
   }
   if(!count)throw new Error("empty_catalog");
   await client.query("delete from catalog_sources");await client.query("insert into catalog_sources(name,source_url,source_url_encrypted,active,updated_at) values($1,null,$2,true,now())",[name,encryptSecret(sourceUrl)]);
   await client.query("commit");await finish("success",null,count,bytes);await audit(req,"catalog_synced","catalog",undefined,{name,items:count,bytes,runId});return {ok:true,items:count,bytes,runId};
  }catch(error:any){
   await client.query("rollback");const code=error?.message==="catalog_too_large"||error?.message==="catalog_item_limit"?error.message:"catalog_sync_failed";await finish("failed",code,count,bytes);req.log.warn({runId,errorCode:code,items:count,bytes},"catalog_sync_failed");
   if(code==="catalog_too_large"||code==="catalog_item_limit")return reply.code(413).send({error:code});
   return reply.code(400).send({error:"catalog_sync_failed"});
  }finally{client.release()}
 });
 app.get("/v1/admin/catalog",{preHandler:master},async()=>{
  const [source,groups,types,sync]=await Promise.all([
   pool.query("select id,name,active,updated_at from catalog_sources order by updated_at desc limit 1"),
   pool.query("select i.group_name as name,count(*)::int items,coalesce(g.content_type,'live') as type from catalog_items i left join catalog_group_types g on g.group_name=i.group_name where i.active=true group by i.group_name,g.content_type order by i.group_name"),
   pool.query("select content_type as type,count(*)::int items from catalog_items where active=true group by content_type order by content_type"),
   pool.query("select id,source_name,status,error_code,items,bytes,duration_ms,started_at,finished_at from catalog_sync_runs order by started_at desc limit 1")
  ]);
  return {source:source.rows[0]??null,groups:groups.rows,types:types.rows,sync:sync.rows[0]??null};
 });
 app.put("/v1/admin/catalog/groups/:group/type",{preHandler:master},async(req:any,reply)=>{const group=decodeURIComponent(String(req.params.group??""));const type=String(req.body?.type??"");if(!group||!["live","movie","series"].includes(type))return reply.code(400).send({error:"invalid_catalog_type"});const exists=await pool.query("select count(*)::int n from catalog_items where active=true and group_name=$1",[group]);if(!exists.rows[0]?.n)return reply.code(404).send({error:"group_not_found"});const client=await pool.connect();try{await client.query("begin");await client.query("insert into catalog_group_types(group_name,content_type,updated_at) values($1,$2,now()) on conflict(group_name) do update set content_type=excluded.content_type,updated_at=now()",[group,type]);const changed=await client.query("update catalog_items set content_type=$2,updated_at=now() where group_name=$1",[group,type]);await client.query("commit");await audit(req,"catalog_group_type_changed","catalog_group",group,{type,items:changed.rowCount??0});return {ok:true,group,type,items:changed.rowCount??0}}catch(e){await client.query("rollback");throw e}finally{client.release()}});

 app.get("/v1/admin/overview",{preHandler:master},async()=>{const [u,d,c]=await Promise.all([pool.query("select count(*)::int n from app_users where role='customer'"),pool.query("select count(*)::int n from devices where active=true"),pool.query("select count(*)::int n from catalog_items where active=true")]);return {customers:u.rows[0].n,devices:d.rows[0].n,catalogItems:c.rows[0].n}});
 app.post("/v1/admin/customers",{preHandler:master},async(req:any,reply)=>{const {name,email,password,expiresAt,deviceLimit}=req.body??{};if(!name||!email||!password)return reply.code(400).send({error:"required_fields"});if(String(password).length<10)return reply.code(400).send({error:"password_too_short"});const limit=Number(deviceLimit??2);if(!Number.isInteger(limit)||limit<1||limit>20)return reply.code(400).send({error:"invalid_device_limit"});const passwordHash=await bcrypt.hash(password,12);try{const r=await pool.query("insert into app_users(role,name,email,password_hash,expires_at,device_limit) values('customer',$1,$2,$3,$4,$5) returning id,name,email,status,expires_at,device_limit",[name,email,passwordHash,expiresAt??null,limit]);await audit(req,"customer_created","customer",r.rows[0].id,{deviceLimit:limit});return reply.code(201).send(r.rows[0])}catch(error){if(dbConflict(error))return reply.code(409).send({error:"email_already_exists"});throw error}});
 app.get("/v1/admin/customers",{preHandler:master},async()=>{const r=await pool.query("select id,name,email,status,expires_at,device_limit,created_at from app_users where role='customer' order by created_at desc");return r.rows});
 app.get("/v1/admin/customers/:id",{preHandler:master},async(req:any,reply)=>{const [customer,devices,sessions,groups]=await Promise.all([pool.query("select id,name,email,status,expires_at,device_limit,created_at from app_users where id=$1 and role='customer'",[req.params.id]),pool.query("select id,name,platform,active,last_seen_at from devices where user_id=$1 order by last_seen_at desc",[req.params.id]),pool.query("select s.id,s.expires_at,s.revoked_at,s.created_at,d.name device_name,d.platform from refresh_sessions s left join devices d on d.id=s.device_id where s.user_id=$1 order by s.created_at desc limit 50",[req.params.id]),pool.query("select c.group_name name,count(*)::int items,coalesce(g.allowed,true) allowed from catalog_items c left join customer_catalog_groups g on g.user_id=$1 and g.group_name=c.group_name where c.active=true group by c.group_name,g.allowed order by c.group_name",[req.params.id])]);if(!customer.rowCount)return reply.code(404).send({error:"not_found"});return {customer:customer.rows[0],devices:devices.rows,sessions:sessions.rows,groups:groups.rows}});
 app.patch("/v1/admin/customers/:id",{preHandler:master},async(req:any,reply)=>{const {name,email,expiresAt,deviceLimit}=req.body??{};const limit=deviceLimit==null?null:Number(deviceLimit);if(limit!=null&&(!Number.isInteger(limit)||limit<1||limit>20))return reply.code(400).send({error:"invalid_device_limit"});let r;try{r=await pool.query("update app_users set name=coalesce($1,name),email=coalesce($2,email),expires_at=case when $6 then $3 else expires_at end,device_limit=coalesce($4,device_limit) where id=$5 and role='customer' returning id,name,email,status,expires_at,device_limit",[name??null,email??null,expiresAt??null,limit,req.params.id,Object.prototype.hasOwnProperty.call(req.body??{},"expiresAt")])}catch(error){if(dbConflict(error))return reply.code(409).send({error:"email_already_exists"});throw error}if(!r.rowCount)return reply.code(404).send({error:"not_found"});await audit(req,"customer_updated","customer",req.params.id,{deviceLimit:limit,expiresAt:expiresAt??null});return r.rows[0]});
 app.put("/v1/admin/customers/:id/catalog-groups",{preHandler:master},async(req:any,reply)=>{
  const groups=Array.isArray(req.body?.groups)?req.body.groups:[];
  const client=await pool.connect();
  try{
   await client.query("begin");
   const customer=await client.query("select 1 from app_users where id=$1 and role='customer' for update",[req.params.id]);
   if(!customer.rowCount){await client.query("rollback");return reply.code(404).send({error:"not_found"})}
   await client.query("delete from customer_catalog_groups where user_id=$1",[req.params.id]);
   for(const g of groups)if(typeof g?.name==="string")await client.query("insert into customer_catalog_groups(user_id,group_name,allowed) values($1,$2,$3)",[req.params.id,g.name,g.allowed!==false]);
   await client.query("commit");
   await audit(req,"customer_catalog_updated","customer",req.params.id,{groups:groups.length});
   return {ok:true};
  }catch(e){await client.query("rollback");throw e}finally{client.release()}
 });
 app.post("/v1/admin/customers/:id/revoke-sessions",{preHandler:master},async(req:any,reply)=>{const client=await pool.connect();try{await client.query("begin");const user=await client.query("update app_users set session_version=session_version+1 where id=$1 and role='customer' returning id",[req.params.id]);if(!user.rowCount){await client.query("rollback");return reply.code(404).send({error:"not_found"})}await client.query("update refresh_sessions set revoked_at=now() where user_id=$1 and revoked_at is null",[req.params.id]);await client.query("commit");await audit(req,"customer_sessions_revoked","customer",req.params.id);return {ok:true}}catch(e){await client.query("rollback");throw e}finally{client.release()}});
 app.post("/v1/admin/customers/:id/extend",{preHandler:master},async(req:any,reply)=>{const days=Number(req.body?.days);if(![30,60,90].includes(days))return reply.code(400).send({error:"invalid_days"});const r=await pool.query("update app_users set expires_at=greatest(coalesce(expires_at,now()),now())+($1::text||' days')::interval,status=case when status='expired' then 'active' else status end where id=$2 and role='customer' returning id,name,email,status,expires_at,device_limit",[days,req.params.id]);if(!r.rowCount)return reply.code(404).send({error:"not_found"});await audit(req,"customer_access_extended","customer",req.params.id,{days});return r.rows[0]});
 app.post("/v1/admin/customers/:id/reset-password",{preHandler:master},async(req:any,reply)=>{const password=String(req.body?.password??"");if(password.length<10)return reply.code(400).send({error:"password_too_short"});const passwordHash=await bcrypt.hash(password,12);const r=await pool.query("update app_users set password_hash=$1,session_version=session_version+1 where id=$2 and role='customer' returning id",[passwordHash,req.params.id]);if(!r.rowCount)return reply.code(404).send({error:"not_found"});await pool.query("update refresh_sessions set revoked_at=now() where user_id=$1 and revoked_at is null",[req.params.id]);await audit(req,"customer_password_reset","customer",req.params.id);return {ok:true}});
 app.patch("/v1/admin/devices/:id/reactivate",{preHandler:master},async(req:any,reply)=>{
  const client=await pool.connect();
  try{
   await client.query("begin");
   const d=await client.query("select d.id,d.user_id,d.active,u.role,u.device_limit from devices d join app_users u on u.id=d.user_id where d.id=$1 for update",[req.params.id]);
   const device=d.rows[0];if(!device||device.role!=="customer"){await client.query("rollback");return reply.code(404).send({error:"not_found"})}
   if(!device.active){const count=await client.query("select count(*)::int n from devices where user_id=$1 and active=true",[device.user_id]);if(count.rows[0].n>=device.device_limit){await client.query("rollback");return reply.code(409).send({error:"device_limit"})}}
   await client.query("update devices set active=true,last_seen_at=now(),session_version=session_version+1 where id=$1",[req.params.id]);
   await client.query("commit");
   await audit(req,"device_reactivated","device",req.params.id,{userId:device.user_id});
   return {ok:true};
  }catch(e){await client.query("rollback");throw e}finally{client.release()}
 });
 app.get("/v1/admin/audit",{preHandler:master},async()=>{const r=await pool.query("select a.id,a.action,a.target_type,a.target_id,a.metadata,a.created_at,u.name actor_name from admin_audit_log a left join app_users u on u.id=a.actor_user_id order by a.created_at desc limit 200");return r.rows});
 app.get("/v1/admin/devices",{preHandler:master},async()=>{const r=await pool.query("select d.id,d.name,d.platform,d.active,d.last_seen_at,u.name customer_name,u.email from devices d join app_users u on u.id=d.user_id where u.role='customer' order by d.last_seen_at desc");return r.rows});
 app.patch("/v1/admin/customers/:id/status",{preHandler:master},async(req:any,reply)=>{const status=String(req.body?.status??"");if(!["active","blocked","expired"].includes(status))return reply.code(400).send({error:"invalid_status"});const r=await pool.query("update app_users set status=$1,session_version=case when $1='active' then session_version else session_version+1 end where id=$2 and role='customer' returning id,name,email,status,expires_at,device_limit",[status,req.params.id]);if(!r.rowCount)return reply.code(404).send({error:"not_found"});if(status!=="active")await pool.query("update refresh_sessions set revoked_at=now() where user_id=$1 and revoked_at is null",[req.params.id]);await audit(req,"customer_status_changed","customer",req.params.id,{status});return r.rows[0]});
 app.patch("/v1/admin/devices/:id/revoke",{preHandler:master},async(req:any,reply)=>{const client=await pool.connect();try{await client.query("begin");const r=await client.query("update devices d set active=false,session_version=d.session_version+1 from app_users u where d.id=$1 and u.id=d.user_id and u.role='customer' returning d.id",[req.params.id]);if(!r.rowCount){await client.query("rollback");return reply.code(404).send({error:"not_found"})}await client.query("update refresh_sessions set revoked_at=now() where device_id=$1 and revoked_at is null",[req.params.id]);await client.query("commit");await audit(req,"device_revoked","device",req.params.id);return {ok:true}}catch(e){await client.query("rollback");throw e}finally{client.release()}});
 return app;
}